services:
  - type: web
    name: thorgodoflightning
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: BASE_URL
        value: https://stack-54k8.onrender.com
    envVarsFromFiles:
      - key: FIREBASE_CREDENTIALS
        fromFile: service-account.json
    healthCheckPath: /health
    autoDeploy: true 