services:
  - type: web
    name: thorgodoflightning
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --log-level debug --access-log
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: true  # Temporarily set to true for debugging
      - key: BASE_URL
        value: https://stack-pjz5.onrender.com
      - key: GOOGLE_CLOUD_PROJECT
        value: "tiktok-18d7a"  # Updated with actual project ID from .env
    envVarsFromFiles:
      - key: FIREBASE_CREDENTIALS
        fromFile: .env
    healthCheckPath: /health
    autoDeploy: true 